package bindings.sdl3;

import cpp.UInt64;
import bindings.sdl3.SDL_Video;
import cpp.Int32;
import cpp.UInt32;

enum abstract SDL_EventType(UInt32) {
	var SDL_EVENT_FIRST;
	var SDL_EVENT_QUIT = 0x100;
	var SDL_EVENT_TERMINATING;
	var SDL_EVENT_LOW_MEMORY;
	var SDL_EVENT_WILL_ENTER_BACKGROUND;
	var SDL_EVENT_DID_ENTER_BACKGROUND;
	var SDL_EVENT_WILL_ENTER_FOREGROUND;
	var SDL_EVENT_DID_ENTER_FOREGROUND;
	var SDL_EVENT_LOCALE_CHANGED;
	var SDL_EVENT_SYSTEM_THEME_CHANGED;

	var SDL_EVENT_DISPLAY_ORIENTATION = 0x151;
	var SDL_EVENT_DISPLAY_ADDED;
	var SDL_EVENT_DISPLAY_REMOVED;
	var SDL_EVENT_DISPLAY_MOVED;
	var SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED;
	var SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED;
	var SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED;
	var SDL_EVENT_DISPLAY_USABLE_BOUNDS_CHANGED;
	var SDL_EVENT_DISPLAY_FIRST = SDL_EVENT_DISPLAY_ORIENTATION;
	var SDL_EVENT_DISPLAY_LAST = SDL_EVENT_DISPLAY_USABLE_BOUNDS_CHANGED;

	var SDL_EVENT_WINDOW_SHOWN = 0x202;
	var SDL_EVENT_WINDOW_HIDDEN;
	var SDL_EVENT_WINDOW_EXPOSED;
	var SDL_EVENT_WINDOW_MOVED;
	var SDL_EVENT_WINDOW_RESIZED;
	var SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED;
	var SDL_EVENT_WINDOW_METAL_VIEW_RESIZED;
	var SDL_EVENT_WINDOW_MINIMIZED;
	var SDL_EVENT_WINDOW_MAXIMIZED;
	var SDL_EVENT_WINDOW_RESTORED;
	var SDL_EVENT_WINDOW_MOUSE_ENTER;
	var SDL_EVENT_WINDOW_MOUSE_LEAVE;
	var SDL_EVENT_WINDOW_FOCUS_GAINED;
	var SDL_EVENT_WINDOW_FOCUS_LOST;
	var SDL_EVENT_WINDOW_CLOSE_REQUESTED;
	var SDL_EVENT_WINDOW_HIT_TEST;
	var SDL_EVENT_WINDOW_ICCPROF_CHANGED;
	var SDL_EVENT_WINDOW_DISPLAY_CHANGED;
	var SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED;
	var SDL_EVENT_WINDOW_SAFE_AREA_CHANGED;
	var SDL_EVENT_WINDOW_OCCLUDED;
	var SDL_EVENT_WINDOW_ENTER_FULLSCREEN;
	var SDL_EVENT_WINDOW_LEAVE_FULLSCREEN;
	var SDL_EVENT_WINDOW_DESTROYED;
	var SDL_EVENT_WINDOW_HDR_STATE_CHANGED;
	var SDL_EVENT_WINDOW_FIRST = SDL_EVENT_WINDOW_SHOWN;
	var SDL_EVENT_WINDOW_LAST = SDL_EVENT_WINDOW_HDR_STATE_CHANGED;

	var SDL_EVENT_KEY_DOWN = 0x300;
	var SDL_EVENT_KEY_UP;
	var SDL_EVENT_TEXT_EDITING;
	var SDL_EVENT_TEXT_INPUT;
	var SDL_EVENT_KEYMAP_CHANGED;
	var SDL_EVENT_KEYBOARD_ADDED;
	var SDL_EVENT_KEYBOARD_REMOVED;
	var SDL_EVENT_TEXT_EDITING_CANDIDATES;
	var SDL_EVENT_SCREEN_KEYBOARD_SHOWN;
	var SDL_EVENT_SCREEN_KEYBOARD_HIDDEN;

	var SDL_EVENT_MOUSE_MOTION = 0x400;
	var SDL_EVENT_MOUSE_BUTTON_DOWN;
	var SDL_EVENT_MOUSE_BUTTON_UP;
	var SDL_EVENT_MOUSE_WHEEL;
	var SDL_EVENT_MOUSE_ADDED;
	var SDL_EVENT_MOUSE_REMOVED;

	var SDL_EVENT_JOYSTICK_AXIS_MOTION = 0x600;
	var SDL_EVENT_JOYSTICK_BALL_MOTION;
	var SDL_EVENT_JOYSTICK_HAT_MOTION;
	var SDL_EVENT_JOYSTICK_BUTTON_DOWN;
	var SDL_EVENT_JOYSTICK_BUTTON_UP;
	var SDL_EVENT_JOYSTICK_ADDED;
	var SDL_EVENT_JOYSTICK_REMOVED;
	var SDL_EVENT_JOYSTICK_BATTERY_UPDATED;
	var SDL_EVENT_JOYSTICK_UPDATE_COMPLETE;

	var SDL_EVENT_GAMEPAD_AXIS_MOTION = 0x650;
	var SDL_EVENT_GAMEPAD_BUTTON_DOWN;
	var SDL_EVENT_GAMEPAD_BUTTON_UP;
	var SDL_EVENT_GAMEPAD_ADDED;
	var SDL_EVENT_GAMEPAD_REMOVED;
	var SDL_EVENT_GAMEPAD_REMAPPED;
	var SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN;
	var SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION;
	var SDL_EVENT_GAMEPAD_TOUCHPAD_UP;
	var SDL_EVENT_GAMEPAD_SENSOR_UPDATE;
	var SDL_EVENT_GAMEPAD_UPDATE_COMPLETE;
	var SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED;

	var SDL_EVENT_FINGER_DOWN = 0x700;
	var SDL_EVENT_FINGER_UP;
	var SDL_EVENT_FINGER_MOTION;
	var SDL_EVENT_FINGER_CANCELED;

	var SDL_EVENT_PINCH_BEGIN = 0x710;
	var SDL_EVENT_PINCH_UPDATE;
	var SDL_EVENT_PINCH_END;

	var SDL_EVENT_CLIPBOARD_UPDATE = 0x900;

	var SDL_EVENT_DROP_FILE = 0x1000;
	var SDL_EVENT_DROP_TEXT;
	var SDL_EVENT_DROP_BEGIN;
	var SDL_EVENT_DROP_COMPLETE;
	var SDL_EVENT_DROP_POSITION;

	var SDL_EVENT_AUDIO_DEVICE_ADDED = 0x1100;
	var SDL_EVENT_AUDIO_DEVICE_REMOVED;
	var SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED;

	var SDL_EVENT_SENSOR_UPDATE = 0x1200;

	var SDL_EVENT_PEN_PROXIMITY_IN = 0x1300;
	var SDL_EVENT_PEN_PROXIMITY_OUT;
	var SDL_EVENT_PEN_DOWN;
	var SDL_EVENT_PEN_UP;
	var SDL_EVENT_PEN_BUTTON_DOWN;
	var SDL_EVENT_PEN_BUTTON_UP;
	var SDL_EVENT_PEN_MOTION;
	var SDL_EVENT_PEN_AXIS;

	var SDL_EVENT_CAMERA_DEVICE_ADDED = 0x1400;
	var SDL_EVENT_CAMERA_DEVICE_REMOVED;
	var SDL_EVENT_CAMERA_DEVICE_APPROVED;
	var SDL_EVENT_CAMERA_DEVICE_DENIED;

	var SDL_EVENT_RENDER_TARGETS_RESET = 0x2000;
	var SDL_EVENT_RENDER_DEVICE_RESET;
	var SDL_EVENT_RENDER_DEVICE_LOST;

	var SDL_EVENT_PRIVATE0 = 0x4000;
	var SDL_EVENT_PRIVATE1;
	var SDL_EVENT_PRIVATE2;
	var SDL_EVENT_PRIVATE3;

	var SDL_EVENT_POLL_SENTINEL = 0x7F00;
	var SDL_EVENT_USER = 0x8000;
	var SDL_EVENT_LAST = 0xFFFF;

	var SDL_EVENT_ENUM_PADDING = 0x7FFFFFFF;
}

@:native("SDL_CommonEvent")
@:include("vendor/include/SDL3/SDL.h")
extern class SDL_CommonEvent {
	@:native("type")
	public var type:UInt32;

	@:native("reversed")
	public var reversed:UInt32;

	@:native("timestamp")
	public var timestamp:UInt64;
}

@:native("SDL_DisplayEvent")
@:include("vendor/include/SDL3/SDL.h")
extern class SDL_DisplayEvent {
	@:native("type")
	public var type:SDL_EventType;

	@:native("reversed")
	public var reversed:UInt32;

	@:native("timestamp")
	public var timestamp:UInt64;

	@:native("displayID")
	public var displayID:SDL_DisplayID;

	@:native("data1")
	public var data1:Int32;

	@:native("data2")
	public var data2:Int32;
}

@:native("SDL_WindowEvent")
@:include("vendor/include/SDL3/SDL.h")
extern class SDL_WindowEvent {
	@:native("type")
	public var type:SDL_EventType;

	@:native("reversed")
	public var reversed:UInt32;

	@:native("timestamp")
	public var timestamp:UInt64;

	@:native("data1")
	public var data1:Int32;

	@:native("data2")
	public var data2:Int32;
}
